### ISSUE TITLE
PM2 error when starting node on docker

### ISSUE THREAD

**Issue by rguikers** [HydraChain/hydrachain#18]
Hi, 

Experimenting with the docker implementation and having a
problem when starting nodes with following command :
```
docker-compose scale statsmon=1 bootstrap=1 node=9
```

statsmon started ok, nodes failing on start :

```
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized

/usr/lib/node_modules/pm2/lib/CLI.js:2305
    if(util.isObject(app.env[key])) {
            ^
TypeError: Object #<Object> has no method 'isObject'
    at mergeEnvironmentVariables (/usr/lib/node_modules/pm2/lib/CLI.js:2305:13)
    at /usr/lib/node_modules/pm2/lib/CLI.js:337:7
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:181:20
    at replenish (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:319:21)
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:330:15
    at Object.async.forEachLimit.async.eachLimit (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:220:35)
    at startApps (/usr/lib/node_modules/pm2/lib/CLI.js:323:11)
    at /usr/lib/node_modules/pm2/lib/CLI.js:423:14
    at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
    at replenish (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:314:29)
```

**Comment by heikoheiko** [comment]
@konradkonrad was this issue resolved?

**Comment by rguikers** [comment]
Hi, Don't know for sure.. new error is (last lines when running docker-compose build) :

```
creating /usr/local/bitcoin
error: can't copy 'bitcoin/english.txt': doesn't exist or not a regular file

----------------------------------------
Command "/usr/local/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-32x9DY/bitcoin/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kumPey-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-32x9DY/bitcoin
```

Service 'node' failed to build: The command '/bin/sh -c pip install -e .' returned a non-zero code: 1
