### ISSUE TITLE
Cython dependency missing

### ISSUE THREAD

**Issue by jorisbontje** [HydraChain/hydrachain#2]
Looks like the `cython` dependency needs to be added to `requirements.txt`

```
$ python setup.py develop
running develop
running egg_info
creating hydrachain.egg-info
writing requirements to hydrachain.egg-info/requires.txt
writing hydrachain.egg-info/PKG-INFO
writing top-level names to hydrachain.egg-info/top_level.txt
writing dependency_links to hydrachain.egg-info/dependency_links.txt
writing entry points to hydrachain.egg-info/entry_points.txt
writing manifest file 'hydrachain.egg-info/SOURCES.txt'
reading manifest file 'hydrachain.egg-info/SOURCES.txt'
writing manifest file 'hydrachain.egg-info/SOURCES.txt'
running build_ext
Creating /Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/hydrachain.egg-link (link to .)
Adding hydrachain 0.0.1 to easy-install.pth file
Installing hydrachain script to /Users/mids/.virtualenvs/hydrachain/bin

Installed /Users/mids/Projects/ethereum/hydrachain
Processing dependencies for hydrachain==0.0.1
Searching for pyethapp
Reading https://pypi.python.org/simple/pyethapp/
Best match: pyethapp 1.0.1
Downloading https://pypi.python.org/packages/source/p/pyethapp/pyethapp-1.0.1.tar.gz#md5=89b91ea0d666e33717a27975640b9292
Processing pyethapp-1.0.1.tar.gz
Writing /var/folders/4s/xhntr1m53w3dlq5pm5d42h600000gn/T/easy_install-iHYocr/pyethapp-1.0.1/setup.cfg
Running pyethapp-1.0.1/setup.py -q bdist_egg --dist-dir /var/folders/4s/xhntr1m53w3dlq5pm5d42h600000gn/T/easy_install-iHYocr/pyethapp-1.0.1/egg-dist-tmp-aav9UY
warning: no files found matching '*' under directory 'tests'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
creating /Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pyethapp-1.0.1-py2.7.egg
Extracting pyethapp-1.0.1-py2.7.egg to /Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages
Adding pyethapp 1.0.1 to easy-install.pth file
Installing pyethapp script to /Users/mids/.virtualenvs/hydrachain/bin

Installed /Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pyethapp-1.0.1-py2.7.egg
Searching for pytest
Reading https://pypi.python.org/simple/pytest/
Best match: pytest 2.7.2
Downloading https://pypi.python.org/packages/source/p/pytest/pytest-2.7.2.tar.gz#md5=dcd8e891474d605b81fc7fcc8711e95b
Processing pytest-2.7.2.tar.gz
Writing /var/folders/4s/xhntr1m53w3dlq5pm5d42h600000gn/T/easy_install-BI90lt/pytest-2.7.2/setup.cfg
Running pytest-2.7.2/setup.py -q bdist_egg --dist-dir /var/folders/4s/xhntr1m53w3dlq5pm5d42h600000gn/T/easy_install-BI90lt/pytest-2.7.2/egg-dist-tmp-v8fT_b
creating /Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pytest-2.7.2-py2.7.egg
Extracting pytest-2.7.2-py2.7.egg to /Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages
Adding pytest 2.7.2 to easy-install.pth file
Installing py.test-2.7 script to /Users/mids/.virtualenvs/hydrachain/bin
Installing py.test script to /Users/mids/.virtualenvs/hydrachain/bin

Installed /Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pytest-2.7.2-py2.7.egg
Searching for ecdsa-recover
Reading https://pypi.python.org/simple/ecdsa-recover/
Best match: ecdsa-recover 0.1.4
Downloading https://pypi.python.org/packages/source/e/ecdsa_recover/ecdsa_recover-0.1.4.tar.gz#md5=690ec12923455503e7b49c3b56015d18
Processing ecdsa_recover-0.1.4.tar.gz
Writing /var/folders/4s/xhntr1m53w3dlq5pm5d42h600000gn/T/easy_install-OhxYJI/ecdsa_recover-0.1.4/setup.cfg
Running ecdsa_recover-0.1.4/setup.py -q bdist_egg --dist-dir /var/folders/4s/xhntr1m53w3dlq5pm5d42h600000gn/T/easy_install-OhxYJI/ecdsa_recover-0.1.4/egg-dist-tmp-V4M4_2
Traceback (most recent call last):
  File "setup.py", line 74, in <module>
    '''
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/command/develop.py", line 32, in run
    self.install_for_development()
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/command/develop.py", line 132, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 703, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pkg_resources/__init__.py", line 797, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1047, in best_match
    return self.obtain(req, installer)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1059, in obtain
    return installer(requirement)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 838, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1066, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1052, in run_setup
    run_setup(setup_script, args)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/sandbox.py", line 238, in run_setup
    raise
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/sandbox.py", line 191, in setup_context
    yield
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/sandbox.py", line 162, in save_modules
    saved_exc.resume()
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/sandbox.py", line 137, in resume
    compat.reraise(type, exc, self._tb)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/sandbox.py", line 150, in save_modules
    yield saved
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/sandbox.py", line 191, in setup_context
    yield
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/sandbox.py", line 235, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/sandbox.py", line 265, in run
    return func()
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/sandbox.py", line 234, in runner
    _execfile(setup_script, ns)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/var/folders/4s/xhntr1m53w3dlq5pm5d42h600000gn/T/easy_install-OhxYJI/ecdsa_recover-0.1.4/setup.py", line 3, in <module>

ImportError: No module named Cython.Build
```

**Comment by heikoheiko** [comment]
fixed in https://github.com/heikoheiko/cy_ecdsa_recover/commit/125987b22605e6c23c6cdbd471cdcc6a3265462c
