### ISSUE TITLE
devp2p PeerManager list index out of range when selecting kademlia neighbour

### ISSUE THREAD

**Issue by jorisbontje** [HydraChain/hydrachain#5]
Following the example rundummy script:
(hydrachain commit fbdaeb881c5ed1666a94ab5cb986da8ab4441108 on OSX)

```
$ hydrachain -d tmp rundummy --num_validators=3 --node_num=0 --seed=42
No handlers could be found for logger "eth.pow"

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

INFO:app	using data in path=tmp
INFO:config	loading config path=tmp
CRITICAL:app	Move to EthApp.default_config
CRITICAL:app	loading profile profile=olympic
CRITICAL:app	done
CRITICAL:app	update genesis config
CRITICAL:app	done
? ''
: {}
accounts:
  keystore_dir: keystore
  privkeys_hex: [09afffe811826df22c1d7f833cf83e6daf7476deb4850c91876e68a33a13c4b8]
client_version: pydevp2p 0.5.1
client_version_string: HydraChain/v0.0.1/darwin/py2.7.10
data_dir: !!python/unicode 'tmp'
db: {implementation: LevelDB}
deactivated_services: [pow]
discovery:
  bootstrap_nodes: ['enode://316d88516ff96ed22251f178684c6ea296d224be06e7ee301d363abd03aa9ad757b0fb647ad726e2367750e0f30c7240b010efe87a1ae9c5e9896f78e8827aff@0.0.0.0:29870']
  listen_host: 0.0.0.0
  listen_port: 29870
eth:
  block:
    BLKLIM_FACTOR_DEN: 2
    BLKLIM_FACTOR_NOM: 3
    BLOCK_DIFF_FACTOR: 2048
    BLOCK_REWARD: 1500000000000000000
    DIFF_ADJUSTMENT_CUTOFF: 8
    EXPDIFF_FREE_PERIODS: 2
    EXPDIFF_PERIOD: 100000
    GASLIMIT_ADJMAX_FACTOR: 1024
    GASLIMIT_EMA_FACTOR: 1024
    GENESIS_COINBASE: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    GENESIS_DIFFICULTY: 131072
    GENESIS_EXTRA_DATA: ''
    GENESIS_GAS_LIMIT: 3141592
    GENESIS_INITIAL_ALLOC:
      '0000000000000000000000000000000000000001': {balance: '1'}
      '0000000000000000000000000000000000000002': {balance: '1'}
      '0000000000000000000000000000000000000003': {balance: '1'}
      '0000000000000000000000000000000000000004': {balance: '1'}
      1a26338f0d905e295fccb71fa9ea849ffa12aaf4: {balance: '1606938044258990275541962092341162602522202993782792835301376'}
      2ef47100e0787b915105fd5e3f4ff6752079d5cb: {balance: '1606938044258990275541962092341162602522202993782792835301376'}
      6c386a4b26f73c802f34673f7248bb118f97424a: {balance: '1606938044258990275541962092341162602522202993782792835301376'}
      b9c015918bdaba24b4ff057a92a3873d6eb201be: {balance: '1606938044258990275541962092341162602522202993782792835301376'}
      cd2a3d9f938e13cd947ec05abc7fe734df8dd826: {balance: '1606938044258990275541962092341162602522202993782792835301376'}
      dbdbdb2cbd23b783741e8d7fcf51e459b497e4a6: {balance: '1606938044258990275541962092341162602522202993782792835301376'}
      e4157b34ea9615cfbde6b4fda419828124b70c78: {balance: '1606938044258990275541962092341162602522202993782792835301376'}
      e6716f9544a56c530d868e4bfbacb172315bdead: {balance: '1606938044258990275541962092341162602522202993782792835301376'}
    GENESIS_MIXHASH: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
      \0\0"
    GENESIS_NONCE: "\0\0\0\0\0\0\0B"
    GENESIS_PREVHASH: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
      \0\0"
    GENESIS_TIMESTAMP: 0
    MAX_EXTRADATA_LENGTH: 32
    MAX_UNCLES: 2
    MAX_UNCLE_DEPTH: 6
    MIN_DIFF: 131072
    MIN_GAS_LIMIT: 125000
    NEPHEW_REWARD: 46875000000000000
    POW_EPOCH_LENGTH: 30000
    UNCLE_DEPTH_PENALTY_FACTOR: 8
  genesis: /Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/pyethapp/data/genesis_olympic.json
  network_id: 0
  pruning: -1
hdc:
  validators:
  - !!binary |
    jtZtDdS4j7CXo6PIwQF1uMrbHGY=
  - !!binary |
    Z9dWG6VUl0GAmjd8O1wS6JdCE5I=
  - !!binary |
    LKf9R/w8lFofQfvD9lyUTfWo9SM=
jsonrpc: {corsdomain: '', listen_host: 127.0.0.1, listen_port: 4000}
node: {privkey_hex: 5d7df279a4187785fa05debac6ca0cc0b4da02ceb37c08132e10ca6a53513f06}
p2p:
  bootstrap_nodes: []
  listen_host: 0.0.0.0
  listen_port: 29870
  max_peers: 10
  min_peers: 2
post_app_start_callback: null

WARNING:accounts	keystore directory does not exist directory=tmp/keystore
WARNING:accounts	no accounts found
INFO:app	registering service service=accounts
INFO:accounts	adding account account=<Account(address=8ed66d0dd4b88fb097a3a3c8c10175b8cadb1c66, id=None)>
INFO:db	opening LevelDB path=tmp/leveldb max_open_files=128 block_cache_size=8388608 write_buffer_size=4194304
INFO:app	registering service service=db
INFO:p2p.discovery	NodeDiscovery init
INFO:p2p.discovery	starting discovery proto this_enode=enode://316d88516ff96ed22251f178684c6ea296d224be06e7ee301d363abd03aa9ad757b0fb647ad726e2367750e0f30c7240b010efe87a1ae9c5e9896f78e8827aff@0.0.0.0:29870
INFO:app	registering service service=discovery
INFO:p2p.peermgr	PeerManager init
INFO:app	registering service service=peermanager
INFO:hdc.chainservice	initializing chain
INFO:hdc.chainservice	chain at number=0
INFO:app	registering service service=chain
INFO:app	registering service service=jsonrpc
INFO:app	registering service service=console
INFO:app	starting
INFO:p2p.peermgr	starting peermanager
INFO:p2p.peermgr	starting listener host=0.0.0.0 port=29870
INFO:p2p.discovery	starting discovery
INFO:p2p.discovery	starting listener host=0.0.0.0 port=29870
INFO:jsonrpc	starting JSONRPCServer port=4000
INFO:p2p.peermgr	waiting for bootstrap
INFO:p2p.peermgr	missing peers known=0 num_peers=0 min_peers=2
Traceback (most recent call last):
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/gevent-1.1b3-py2.7-macosx-10.10-x86_64.egg/gevent/greenlet.py", line 519, in run
    result = self._run(*self.args, **self.kwargs)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/devp2p-0.5.1-py2.7.egg/devp2p/peermanager.py", line 176, in _run
    node = neighbours[0]
IndexError: list index out of range
<PeerManager at 0x101f44cd0> failed with IndexError

Traceback (most recent call last):
  File "/Users/mids/.virtualenvs/hydrachain/bin/hydrachain", line 9, in <module>
    load_entry_point('hydrachain==0.0.1', 'console_scripts', 'hydrachain')()
  File "/Users/mids/Projects/ethereum/hydrachain/hydrachain/app.py", line 148, in app
    pyethapp_app.app()
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/click-5.1-py2.7.egg/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/mids/Projects/ethereum/hydrachain/hydrachain/app.py", line 141, in rundummy
    evt.wait()
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/gevent-1.1b3-py2.7-macosx-10.10-x86_64.egg/gevent/event.py", line 86, in wait
    result = self.hub.switch()
  File "/Users/mids/.virtualenvs/hydrachain/lib/python2.7/site-packages/gevent-1.1b3-py2.7-macosx-10.10-x86_64.egg/gevent/hub.py", line 510, in switch
    return greenlet.switch(self)
IndexError: list index out of range
```

**Comment by heikoheiko** [comment]
fixed in https://github.com/ethereum/pydevp2p/commit/bf324ec200ca311b0ca8725a03f7408e81033778
