### ISSUE TITLE
Reading Scalar from Struct in native contracts throws EncodingError

### ISSUE THREAD

**Issue by 4gn3s** [HydraChain/hydrachain#70]
I've created a simple contract with Scalars in Struct:

``` python
from ethereum import slogging
import ethereum.utils as utils
import hydrachain.native_contracts as nc

from hydrachain.nc_utils import FORBIDDEN, STATUS
from hydrachain.nc_utils import OK, isaddress


log = slogging.get_logger('contracts.test_contract')


class StructContract(nc.NativeContract):
    address = utils.int_to_addr(5000)

    data = nc.Struct(
        x=nc.Scalar('uint256'),
        y=nc.Scalar('uint256')
    )
    z = nc.Scalar('uint256')

    def init(ctx, _init_x='uint256', _init_y='uint256', _init_z='uint256', returns=STATUS):
        ctx.data.x = _init_x
        ctx.data.y = _init_y
        ctx.z = _init_z
        return OK

    def get_x(ctx, returns='uint256'):
        return ctx.data.x

    @nc.constant
    def get_y(ctx, returns='uint256'):
        return ctx.data.y

    @nc.constant
    def get_z(ctx, returns='uint256'):
        return ctx.z
```

and I'm testing the contract with the following test:

``` python
from ethereum import tester

import hydrachain.native_contracts as nc
from struct_contract import StructContract


def test_test_instance():
    state = tester.state()
    creator_address = tester.a0
    creator_key = tester.k0

    nc.registry.register(StructContract)

    # Create proxy
    test_address = nc.tester_create_native_contract_instance(state, creator_key, StructContract)
    contract_instance = nc.tester_nac(state, creator_key, test_address)
    x = 19
    y = 987
    z = 12345
    contract_instance.init(x, y, z)

    assert contract_instance.get_z() == z
    assert contract_instance.get_x() == x
    assert contract_instance.get_y() == y

    nc.registry.unregister(StructContract)
```

I'm able to read _z_, but the assertion with _x_ fails with the following output:

```
/home/agnieszka/.virtualenvs/hydrachain-fork/bin/python /opt/pycharm-community-2016.1/helpers/pycharm/pytestrunner.py -p pytest_teamcity /home/agnieszka/Sources/hydrachain-fork/hydrachain/tests/test_struct_contract.py "-k test_test_instance"
Testing started at 14:51 ...
============================= test session starts ==============================
platform linux2 -- Python 2.7.11+, pytest-2.8.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/agnieszka/Sources/hydrachain-fork, inifile: 
collected 1 items

Sources/hydrachain-fork/hydrachain/tests/test_struct_contract.py DEBUG:eth.chain.tx deserialized tx tx=0342ed16
DEBUG:eth.pb.tx TX NEW tx_dict={'nonce': 0, 'hash': 'be441c1087df2647416c122d434d4b78bc5ff120467f0161fbc83c1d9f48160e', 'sender': '82a978b3f5962a5b0957d9ee9eef472ee55b42f1', 'startgas': 3141592, 'value': 0, 'to': '0000000000000000000000000000000000000400', 's': 20254294983356178048045266962141317841012138312792516662221376766510459988701L, 'r': 53390102416208093712037551204071007295761720606943298823677190293391304140592L, 'v': 27, 'data': '00001388', 'gasprice': 1}
WARNING:nc  method not found, calling default methodid=0
DEBUG:eth.pb.tx _res_ data=[0, 0, 0, 0, 195, 5, 201, 1, 7, 135, 129, 194, 50, 162, 165, 33, 0, 0, 19, 136] result=1 gas_remained=3120448
DEBUG:eth.pb.tx TX APPLIED data=[0, 0, 0, 0, 195, 5, 201, 1, 7, 135, 129, 194, 50, 162, 165, 33, 0, 0, 19, 136] result=1 gas_remained=3120448
DEBUG:eth.pb.tx TX SUCCESS data=[0, 0, 0, 0, 195, 5, 201, 1, 7, 135, 129, 194, 50, 162, 165, 33, 0, 0, 19, 136]
DEBUG:eth.chain.tx  deserialized tx tx=656901af
DEBUG:eth.pb.tx TX NEW tx_dict={'nonce': 1, 'hash': '69b2a3c93d71222f7ca2bedabb266c99e13a8ffca04080f4086052bb031a325b', 'sender': '82a978b3f5962a5b0957d9ee9eef472ee55b42f1', 'startgas': 3141592, 'value': 0, 'to': '00000000c305c901078781c232a2a52100001388', 's': 13046810922808066096960284904484979088517961277186872430013872968397390307242L, 'r': 92310483284741087254013242190125215560022329979398128261087476452753131656623L, 'v': 28, 'data': '8cd8db8a000000000000000000000000000000000000000000000000000000000000001300000000000000000000000000000000000000000000000000000000000003db0000000000000000000000000000000000000000000000000000000000003039', 'gasprice': 1}
INFO:contracts.test_contract    test contract init 
DEBUG:eth.pb.tx _res_ data=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200] result=1 gas_remained=3119616
DEBUG:eth.pb.tx TX APPLIED data=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200] result=1 gas_remained=3119616
DEBUG:eth.pb.tx TX SUCCESS data=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200]
DEBUG:eth.chain.tx  deserialized tx tx=3f973e79
DEBUG:eth.pb.tx TX NEW tx_dict={'nonce': 2, 'hash': '4ebbf38547ff86f163dc018c1d68c7021b3147a46a18e1dbccbd099b1f40f653', 'sender': '82a978b3f5962a5b0957d9ee9eef472ee55b42f1', 'startgas': 3141592, 'value': 0, 'to': '00000000c305c901078781c232a2a52100001388', 's': 40197523223647690289750355119675497217647697594491846594176057757042101027219L, 'r': 9081063719057398610890093229564275172026302107722808935744751720045379029108L, 'v': 28, 'data': '48f27978', 'gasprice': 1}
DEBUG:eth.pb.tx _res_ data=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 57] result=1 gas_remained=3120320
DEBUG:eth.pb.tx TX APPLIED data=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 57] result=1 gas_remained=3120320
DEBUG:eth.pb.tx TX SUCCESS data=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 57]
DEBUG:eth.chain.tx  deserialized tx tx=a8585b78
DEBUG:eth.pb.tx TX NEW tx_dict={'nonce': 3, 'hash': 'c94a130b50b484463906f1bf8a68014de402472af056641843998eae4b2c0d52', 'sender': '82a978b3f5962a5b0957d9ee9eef472ee55b42f1', 'startgas': 3141592, 'value': 0, 'to': '00000000c305c901078781c232a2a52100001388', 's': 42553268189212806898002432477969914199576660278681466457488288367254589666663L, 'r': 40892011021388384056054800714242174805698307308800949896594387680848575504310L, 'v': 28, 'data': '3829050a', 'gasprice': 1}
ERROR:nc    contract errored contract=StructContract
Traceback (most recent call last):
  File "/home/agnieszka/Sources/hydrachain-fork/hydrachain/native_contracts.py", line 130, in _on_msg
    return nac._safe_call()
  File "/home/agnieszka/Sources/hydrachain-fork/hydrachain/native_contracts.py", line 438, in _safe_call
    return 1, self.gas, memoryview(abi_encode_return_vals(method, res)).tolist()
  File "/home/agnieszka/Sources/hydrachain-fork/hydrachain/native_contracts.py", line 241, in abi_encode_return_vals
    return abi.encode_abi(return_types, vals)
  File "/home/agnieszka/.virtualenvs/hydrachain-fork/local/lib/python2.7/site-packages/ethereum/abi.py", line 369, in encode_abi
    myhead += enc(proctypes[i], args[i])
  File "/home/agnieszka/.virtualenvs/hydrachain-fork/local/lib/python2.7/site-packages/ethereum/abi.py", line 344, in enc
    return utils.to_string(encode_single(typ, arg))
  File "/home/agnieszka/.virtualenvs/hydrachain-fork/local/lib/python2.7/site-packages/ethereum/abi.py", line 179, in encode_single
    i = decint(arg, False)
  File "/home/agnieszka/.virtualenvs/hydrachain-fork/local/lib/python2.7/site-packages/ethereum/abi.py", line 171, in decint
    raise EncodingError("Cannot encode integer: %r" % n)
EncodingError: Cannot encode integer: <hydrachain.native_contracts.Scalar object at 0x7f4477e10710>

DEBUG:eth.pb.msg    REVERTING 
DEBUG:eth.pb.tx _res_ data=[] result=0 gas_remained=3120320
DEBUG:eth.pb.tx TX APPLIED data=[] result=0 gas_remained=3120320
DEBUG:eth.pb.tx TX FAILED reason=out of gas startgas=3141592 gas_remained=3120320
F
def test_test_instance():
        state = tester.state()
        creator_address = tester.a0
        creator_key = tester.k0

        nc.registry.register(StructContract)

        # Create proxy
        test_address = nc.tester_create_native_contract_instance(state, creator_key, StructContract)
        contract_instance = nc.tester_nac(state, creator_key, test_address)
        x = 19
        y = 987
        z = 12345
        contract_instance.init(x, y, z)

        assert contract_instance.get_z() == z
>       assert contract_instance.get_x() == x

Sources/hydrachain-fork/hydrachain/tests/test_struct_contract.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Sources/hydrachain-fork/hydrachain/native_contracts.py:546: in m
    r = state._send(sender, address, value=value, evmdata=data)['output']
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ethereum.tester.state instance at 0x7f4475bdf4d0>
sender = '\x04HR\xb2\xa6p\xad\xe5@~x\xfb(c\xc5\x1d\xe9\xfc\xb9eB\xa0q\x86\xfe:\xed\xa6\xbb\x8a\x11m'
to = '\x00\x00\x00\x00\xc3\x05\xc9\x01\x07\x87\x81\xc22\xa2\xa5!\x00\x00\x13\x88'
value = 0, evmdata = '8)\x05\n', output = None, funid = None, abi = None
profiling = 0

    def _send(self, sender, to, value, evmdata='', output=None,
              funid=None, abi=None, profiling=0):
        if funid is not None or abi is not None:
            raise Exception("Send with funid+abi is deprecated. Please use"
                            " the abi_contract mechanism")
        tm, g = time.time(), self.block.gas_used
        sendnonce = self.block.get_nonce(u.privtoaddr(sender))
        tx = t.Transaction(sendnonce, gas_price, gas_limit, to, value, evmdata)
        self.last_tx = tx
        tx.sign(sender)
        recorder = None
        if profiling > 1:
            recorder = LogRecorder(disable_other_handlers=True, log_config=TRACE_LVL_MAP[3])
        try:
            (s, o) = pb.apply_transaction(self.block, tx)
            if not s:
>               raise TransactionFailed()
E               TransactionFailed

.virtualenvs/hydrachain-fork/local/lib/python2.7/site-packages/ethereum/tester.py:214: TransactionFailed


=================================== FAILURES ===================================
______________________________ test_test_instance ______________________________

    def test_test_instance():
        state = tester.state()
        creator_address = tester.a0
        creator_key = tester.k0

        nc.registry.register(StructContract)

        # Create proxy
        test_address = nc.tester_create_native_contract_instance(state, creator_key, StructContract)
        contract_instance = nc.tester_nac(state, creator_key, test_address)
        x = 19
        y = 987
        z = 12345
        contract_instance.init(x, y, z)

        assert contract_instance.get_z() == z
>       assert contract_instance.get_x() == x

Sources/hydrachain-fork/hydrachain/tests/test_struct_contract.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Sources/hydrachain-fork/hydrachain/native_contracts.py:546: in m
    r = state._send(sender, address, value=value, evmdata=data)['output']
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ethereum.tester.state instance at 0x7f4475bdf4d0>
sender = '\x04HR\xb2\xa6p\xad\xe5@~x\xfb(c\xc5\x1d\xe9\xfc\xb9eB\xa0q\x86\xfe:\xed\xa6\xbb\x8a\x11m'
to = '\x00\x00\x00\x00\xc3\x05\xc9\x01\x07\x87\x81\xc22\xa2\xa5!\x00\x00\x13\x88'
value = 0, evmdata = '8)\x05\n', output = None, funid = None, abi = None
profiling = 0

    def _send(self, sender, to, value, evmdata='', output=None,
              funid=None, abi=None, profiling=0):
        if funid is not None or abi is not None:
            raise Exception("Send with funid+abi is deprecated. Please use"
                            " the abi_contract mechanism")
        tm, g = time.time(), self.block.gas_used
        sendnonce = self.block.get_nonce(u.privtoaddr(sender))
        tx = t.Transaction(sendnonce, gas_price, gas_limit, to, value, evmdata)
        self.last_tx = tx
        tx.sign(sender)
        recorder = None
        if profiling > 1:
            recorder = LogRecorder(disable_other_handlers=True, log_config=TRACE_LVL_MAP[3])
        try:
            (s, o) = pb.apply_transaction(self.block, tx)
            if not s:
>               raise TransactionFailed()
E               TransactionFailed

.virtualenvs/hydrachain-fork/local/lib/python2.7/site-packages/ethereum/tester.py:214: TransactionFailed
=========================== 1 failed in 0.55 seconds ===========================

Process finished with exit code 0
```

**Comment by RomanZacharia** [comment]
The issue was resolved in the following PR https://github.com/HydraChain/hydrachain/pull/54
